package com.pmb.ballon.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)


object Color {
    object Light {
        val LOnForegroundNeutralDefault = Color(0xFFFFFFFF)
        val OnForegroundNeutralDisabled = Color(0xFF9B9BA1)
        val OnForegroundNeutralCTA = Color(0xFF90CAF9)
        val StrokeInverted1 = Color(0xFFFFFFFF)
        val StrokeInverted2 = Color(0xFFFFFFFF)
        val ForegroundNeutralDefault = Color(0xFF161618)
        val ForegroundNeutralDisabled = Color(0xFFE2E2E4)
        val ForegroundPrimaryDefault = Color(0xFFC11332)
        val ForegroundSuccessDefault = Color(0xFF388E3C)
        val StrokeNeutral2Default = Color(0xFFE2E2E4)
        val StrokeNeutral2Active = Color(0xFF161618)
        val StrokeNeutral2Error = Color(0xFFB71C1C)
        val StrokeNeutral1Default = Color(0xFFD4D4D7)
        val StrokeNeutral3Rest = Color(0xFFE9E9EB)
        val OnBackgroundTintPrimaryDefault = Color(0xFF810D21)
        val OnBackgroundTintPrimaryDisabled = Color(0xFFE35B73)
        val OnBackgroundPrimaryActive = Color(0xFF161618)
        val OnBackgroundPrimaryDisabled = Color(0xFFC6C6C9)
        val OnBackgroundPrimaryCTA = Color(0xFFC11332)
        val OnBackgroundPrimaryDefault = Color(0xFF161618)
        val OnBackgroundPrimarySubdued = Color(0xFF5A5A61)
        val OnBackgroundErrorDefault = Color(0xFF971111)
        val OnBackgroundErrorDisabled = Color(0xFFEF9A9A)
        val OnBackgroundErrorSubdued = Color(0xFFD32F2F)
        val OnBackgroundWarningDefault = Color(0xFF2A2001)
        val OnBackgroundWarningDisabled = Color(0xFFFFE083)
        val OnBackgroundWarningSubdued = Color(0xFFAA8004)
        val BackgroundTintNeutralDefault = Color(0xFFF0F0F1)
        val BackgroundTintSuccessDefault = Color(0xFFA5D6A7)
        val BackgroundTintWarningDefault = Color(0xFFFFE083)
        val BackgroundTintErrorDefault = Color(0xFFFFCDD2)
        val OnBackgroundTintWarningDefault = Color(0xFF7F6003)
        val OnBackgroundTintErrorRest = Color(0xFF971111)
        val OnBackgroundTintNeutralDefault = Color(0xFF0B0B0C)
        val OnBackgroundTintSuccessDefault = Color(0xFF1B5E20)
        val BackgroundTintPrimaryDefault = Color(0xFFF7D0D7)
        val StateLayerPrimaryHovered = Color(0xC1112E0F)
        val StateLayerPrimaryPressed = Color(0xC1112E1A)
        val StateLayerNeutralHovered = Color(0x0D0D0D0A)
        val StateLayerNeutralPressed = Color(0x0D0D0D14)
        val StateLayerNeutralModalBackground = Color(0x0D0D0D8F)
        val StateLayerInvertedHovered = Color(0xFFFFFF14)
        val StateLayerInvertedPressed = Color(0xFFFFFF1F)
        val Background1Neutral = Color(0xFFFFFFFF)
        val Background2Neutral = Color(0xFFF7F7F8)
        val Background2Primary = Color(0xFFFBE7EB)
        val Background3Neutral = Color(0xFFF0F0F1)
        val OnBackgroundSuccessSubdued = Color(0xFF388E3C)
        val OnBackgroundSuccessDisabled = Color(0xFFA5D6A7)
        val OnBackgroundSuccessDefault = Color(0xFF164D1A)
        val OnBackgroundNeutralDefault = Color(0xFF161618)
        val OnBackgroundNeutralSubdued = Color(0xFF5A5A61)
        val OnBackgroundNeutralActive = Color(0xFF161618)
        val OnBackgroundNeutralCTA = Color(0xFFC11332)
        val OnBackgroundNeutralDisabled = Color(0xFFC6C6C9)
        val ForegroundErrorDefault = Color(0xFFD32F2F)
        val ForegroundWarningDefault = Color(0xFFAA8004)
    }

    object Dark {
        val LOnForegroundNeutralDefault = Color(0xFF2D2D30)
        val OnForegroundNeutralDisabled = Color(0xFF2D2D30)
        val OnForegroundNeutralCTA = Color(0xFFFFFFFF)
        val StrokeInverted1 = Color(0xFF2D2D30)
        val StrokeInverted2 = Color(0xFF2D2D30)
        val ForegroundNeutralDefault = Color(0xFFB8B8BC)
        val ForegroundNeutralDisabled = Color(0xFF434349)
        val ForegroundPrimaryDefault = Color(0xFF550816)
        val ForegroundSuccessDefault = Color(0xFF144111)
        val StrokeNeutral2Default = Color(0xFF434349)
        val StrokeNeutral2Active = Color(0xFF2D2D30)
        val StrokeNeutral2Error = Color(0xFFE53935)
        val StrokeNeutral1Default = Color(0xFFCCCCCC)
        val StrokeNeutral3Rest = Color(0xFF434349)
        val OnBackgroundTintPrimaryDefault = Color(0xFF550816)
        val OnBackgroundTintPrimaryDisabled = Color(0xFFFFFFFF)
        val OnBackgroundPrimaryActive = Color(0xFF550816)
        val OnBackgroundPrimaryDisabled = Color(0xFF2D2D30)
        val OnBackgroundPrimaryCTA = Color(0xFF550816)
        val OnBackgroundPrimaryDefault = Color(0xFFFFFFFF)
        val OnBackgroundPrimarySubdued = Color(0xFFFFFFFF)
        val OnBackgroundErrorDefault = Color(0xFFFFFFFF)
        val OnBackgroundErrorDisabled = Color(0xFFFFFFFF)
        val OnBackgroundErrorSubdued = Color(0xFFFFFFFF)
        val OnBackgroundWarningDefault = Color(0xFFFFFFFF)
        val OnBackgroundWarningDisabled = Color(0xFFFFFFFF)
        val OnBackgroundWarningSubdued = Color(0xFFFFFFFF)
        val BackgroundTintNeutralDefault = Color(0xFF2D2D30)
        val BackgroundTintSuccessDefault = Color(0xFF388E3C)
        val BackgroundTintWarningDefault = Color(0xFFA13900)
        val BackgroundTintErrorDefault = Color(0xFF7B0102)
        val OnBackgroundTintWarningDefault = Color(0xFF732900)
        val OnBackgroundTintErrorRest = Color(0xFF7B0102)
        val OnBackgroundTintNeutralDefault = Color(0xFF434349)
        val OnBackgroundTintSuccessDefault = Color(0xFF388E3C)
        val BackgroundTintPrimaryDefault = Color(0xFF5A5A61)
        val StateLayerPrimaryHovered = Color(0xFFFFFFFF)
        val StateLayerPrimaryPressed = Color(0xFFFFFFFF)
        val StateLayerNeutralHovered = Color(0xFFFFFFFF)
        val StateLayerNeutralPressed = Color(0xFFFFFFFF)
        val StateLayerNeutralModalBackground = Color(0xFFFFFFFF)
        val StateLayerInvertedHovered = Color(0xFFFFFFFF)
        val StateLayerInvertedPressed = Color(0xFFFFFFFF)
        val Background1Neutral = Color(0xFFFFFFFF)
        val Background2Neutral = Color(0xFFFFFFFF)
        val Background2Primary = Color(0xFFFFFFFF)
        val Background3Neutral = Color(0xFFFFFFFF)
        val OnBackgroundSuccessSubdued = Color(0xFFFFFFFF)
        val OnBackgroundSuccessDisabled = Color(0xFFFFFFFF)
        val OnBackgroundSuccessDefault = Color(0xFFFFFFFF)
        val OnBackgroundNeutralDefault = Color(0xFFFFFFFF)
        val OnBackgroundNeutralSubdued = Color(0xFFFFFFFF)
        val OnBackgroundNeutralActive = Color(0xFF550816)
        val OnBackgroundNeutralCTA = Color(0xFF550816)
        val OnBackgroundNeutralDisabled = Color(0xFF2D2D30)
        val ForegroundErrorDefault = Color(0xFF550816)
        val ForegroundWarningDefault = Color(0xFF550816)
    }
}